# typed: false
# frozen_string_literal: true

# GENERATED by scripts/gen_formula.py in mburgs/pr-walkthrough — do not edit.
# Published from a version tag (`v*`) on mburgs/pr-walkthrough. Versions are
# UTC timestamps (YYYY.MM.DD.HHMMSS) so `brew upgrade` always sorts the newest
# release highest.
class PrWalkthrough < Formula
  include Language::Python::Virtualenv

  desc "Narrated, browser-based walkthrough of a GitHub pull request"
  homepage "https://github.com/mburgs/pr-walkthrough"
  url "https://github.com/mburgs/homebrew-pr-walkthrough/releases/download/v2026.10.05.185747/pr_walkthrough_backend-0.1.0-py3-none-any.whl", using: :nounzip
  version "2026.10.05.185747"
  sha256 "2f7b1c458e433465abed55278c48136376c17a8ef68ad75742c0ca4d029068d4"
  license "MIT"

  bottle do
    root_url "https://github.com/mburgs/homebrew-pr-walkthrough/releases/download/v2026.10.05.185747"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "e6b4b7926ade1ee2e296ca6086a58c741342ec4418da0f0d7e085e1b0edae2d4"
  end

  # Apple-Silicon-only: local STT runs on MLX, which ships arm64-only wheels
  # and has no fallback engine (the app hard-fails at startup otherwise).
  depends_on arch: :arm64
  depends_on :macos
  depends_on "python@3.13"

  def install
    # Source fallback (used only when no matching bottle is available). Create
    # the virtualenv, then install the wheel WITH its PyPI dependencies. We do
    # NOT use Homebrew's `venv.pip_install`: it forces `--no-deps
    # --no-binary=:all:` (the resource-vendoring model), which skips deps and
    # source-builds everything — impossible for the mlx/torch stack. Invoking
    # pip directly resolves deps from PyPI as prebuilt wheels. `:nounzip` (on
    # the url) keeps the .whl staged as a file rather than unzipping it.
    #
    # system_site_packages: false is load-bearing for bottling. With the
    # default (true) venv, pip treats any dep already present in the build
    # machine's global site-packages as satisfied and skips installing it into
    # the venv — so the bottle (which tars only the venv) ships incomplete and
    # imports like pydantic_core fail on other machines. An isolated venv
    # forces the full dependency tree into the keg.
    virtualenv_create(libexec, "python3.13", system_site_packages: false)
    system Formula["python@3.13"].opt_bin/"python3.13", "-m", "pip",
           "--python=#{libexec}/bin/python", "install", "--verbose",
           Dir["#{buildpath}/*.whl"].first
    bin.install_symlink Dir["#{libexec}/bin/pr-walkthrough*"]
    bin.install_symlink "#{libexec}/bin/pr-context"
  end

  def caveats
    <<~EOS
      pr-walkthrough needs an Anthropic API key and the GitHub CLI (`gh`) authed:

        export ANTHROPIC_API_KEY=sk-ant-...
        gh auth login

      Optional one-time setup (higher-quality TTS voice, STT warmup, LSPs):

        pr-walkthrough setup

      Update later with:  brew upgrade pr-walkthrough
    EOS
  end

  test do
    system bin/"pr-walkthrough", "--help"
  end
end
